### ISSUE TITLE
Updated forge support

### ISSUE THREAD

**Issue by nheath** [dannydjdk/Tiny-Redstone#105]
Minecraft fails to laod with updated forge, I believe due to breaking changes in multiple recent versions of forge, 41.0.64 and  41.0.94 

Relevant logs:

```
[21Jul2022 20:53:12.505] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[21Jul2022 20:53:12.777] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Games/Minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2390!/ Service=ModLauncher Env=CLIENT
...
[21Jul2022 20:53:16.191] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, forge-41.0.100, --gameDir, C:\Games\Minecraft\Instances\1.19-forge, --assetsDir, C:\Games\Minecraft\Install\assets, --uuid, 662a31463c5e47289c9558b8a355903e, --username, cheekoli, --assetIndex, 1.19, --accessToken, ????????, --clientId, Y2RiMDA0NmUtZmJlOS00MDM0LWExZDEtZjljMGFiOWYyZjlk, --xuid, 2533274866784120, --userType, msa, --versionType, release, --width, 1920, --height, 1080]
[21Jul2022 20:53:20.983] [pool-3-thread-1/INFO] [net.minecraft.util.datafix.DataFixers/]: Building unoptimized datafixer
[21Jul2022 20:53:23.635] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResources/]: Assets URL 'union:/C:/Games/Minecraft/Install/libraries/net/minecraft/client/1.19-20220607.102129/client-1.19-20220607.102129-srg.jar%23204!/assets/.mcassetsroot' uses unexpected schema
[21Jul2022 20:53:23.635] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResources/]: Assets URL 'union:/C:/Games/Minecraft/Install/libraries/net/minecraft/client/1.19-20220607.102129/client-1.19-20220607.102129-srg.jar%23204!/data/.mcassetsroot' uses unexpected schema
[21Jul2022 20:53:23.670] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21Jul2022 20:53:24.088] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: cheekoli
[21Jul2022 20:53:24.273] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.3.1 build 7
[21Jul2022 20:53:25.298] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: tinyredstone, class com.dannyandson.tinyredstone.TinyRedstone
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.100.jar%23206!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.100.jar%23205!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NoSuchFieldError: BLOCK_ENTITIES
	at com.dannyandson.tinyredstone.setup.Registration.<clinit>(Registration.java:29) ~[tinyredstone-1.19-4.0.0.jar%23193!/:1.19-4.0.0]
	at com.dannyandson.tinyredstone.TinyRedstone.<init>(TinyRedstone.java:29) ~[tinyredstone-1.19-4.0.0.jar%23193!/:1.19-4.0.0]
	... 14 more
```

**Comment by dannydjdk** [comment]
Thanks for the report! It looks like forge did some renames in 41.0.94.

**Comment by dannydjdk** [comment]
Update posted 1.19-4.1.0.
Will close when Curseforge approves new version.

**Comment by nheath** [comment]
Did this also affect Tiny-Gates?

**Comment by dannydjdk** [comment]
Haven't tested it yet, but it's highly likely. I'll be testing all my mods this weekend.

**Comment by dannydjdk** [comment]
Tiny Gates is not broken. Not update needed.
Tiny Pipes, Ranged Wireless Redstone and Nutritional Balance are all broken and will be updated soon.

**Comment by nheath** [comment]
thanks!
